QLHoiThaoProject/Models/EFModel/SINHVIEN.cs
namespace QLHoiThaoProject.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("SINHVIEN")]
    public partial class SINHVIEN
    {
        [Key]
        public int IDSV { get; set; }

        public int IDLOP { get; set; }

        [StringLength(255)]
        public string HOTEN { get; set; }

        [StringLength(255)]
        public string EMAIL { get; set; }

        [StringLength(255)]
        public string SDT { get; set; }

        public virtual LOP LOP { get; set; }
    }
}

QLHoiThaoProject/Areas/Admin/Controllers/SINHVIENsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLHoiThaoProject.Models;
using QLHoiThaoProject.Models.EFModel;
using PagedList;

namespace QLHoiThaoProject.Areas.Admin.Controllers
{
    public class SINHVIENsController : BaseController
    {
        private QLHoiThaoDbContext db = new QLHoiThaoDbContext();

        // GET: Admin/SINHVIENs
        public ActionResult Index(int? page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 3;
            ViewBag.Count = db.SINHVIENs.ToList().Count;
            return View(db.SINHVIENs.ToList().OrderBy(p => p.IDLOP).ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Search(int? page, string Name = "")
        {
            var model = db.SINHVIENs.Where(p => p.HOTEN.Contains(Name) || p.EMAIL.Contains(Name) || p.LOP.TENLOP.Contains(Name) || p.SDT.Contains(Name));
            int pageNumber = (page ?? 1);
            int pageSize = 3;
            ViewBag.Count = model.ToList().Count;
            return View(model.OrderBy(p => p.IDLOP).ToList().ToPagedList(pageNumber, pageSize));
        }

        // GET: Admin/SINHVIENs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SINHVIEN sINHVIEN = db.SINHVIENs.Find(id);
            if (sINHVIEN == null)
            {
                return HttpNotFound();
            }
            return View(sINHVIEN);
        }

        // GET: Admin/SINHVIENs/Create
        public ActionResult Create()
        {
            ViewBag.IDLOP = new SelectList(db.LOPs, "IDLOP", "TENLOP");
            return View();
        }

        // POST: Admin/SINHVIENs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDSV,IDLOP,HOTEN,EMAIL,SDT")] SINHVIEN sINHVIEN)
        {
            if (ModelState.IsValid)
            {
                db.SINHVIENs.Add(sINHVIEN);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IDLOP = new SelectList(db.LOPs, "IDLOP", "TENLOP", sINHVIEN.IDLOP);
            return View(sINHVIEN);
        }

        // GET: Admin/SINHVIENs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SINHVIEN sINHVIEN = db.SINHVIENs.Find(id);
            if (sINHVIEN == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDLOP = new SelectList(db.LOPs, "IDLOP", "TENLOP", sINHVIEN.IDLOP);
            return View(sINHVIEN);
        }

        // POST: Admin/SINHVIENs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDSV,IDLOP,HOTEN,EMAIL,SDT")] SINHVIEN sINHVIEN)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sINHVIEN).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDLOP = new SelectList(db.LOPs, "IDLOP", "TENLOP", sINHVIEN.IDLOP);
            return View(sINHVIEN);
        }

        // GET: Admin/SINHVIENs/Delete/5
        public ActionResult Delete(int? id)
        {
            SINHVIEN sINHVIEN = db.SINHVIENs.Find(id);
            return View(sINHVIEN);
        }

        // POST: Admin/SINHVIENs/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            SINHVIEN sINHVIEN = db.SINHVIENs.Find(id);
            db.SINHVIENs.Remove(sINHVIEN);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLHoiThaoProject/Areas/Admin/Views/SINHVIENs/Create.cshtml
@model QLHoiThaoProject.Models.EFModel.SINHVIEN

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section IndexAdmin{
    Quản lý Sinh viên
}

<div class="row">
    <ol class="breadcrumb">
        <li class="active">Thêm sinh viên mới</li>
    </ol>
</div><!--/.row-->

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="control-label col-md-2">Tên lớp</div>
            <div class="col-md-10">
                @Html.DropDownList("IDLOP", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDLOP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Họ tên</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.HOTEN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HOTEN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Email</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Số điện thoại</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button class="btn" type="submit">@Html.ActionLink("Hủy", "Index","SINHVIENs")</button>
                <input type="submit" value="Thêm" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

QLHoiThaoProject/Areas/Admin/Views/SINHVIENs/Details.cshtml
@model QLHoiThaoProject.Models.EFModel.SINHVIEN

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section IndexAdmin{
    Quản lý Sinh viên
}

<div class="row">
    <ol class="breadcrumb">
        <li class="active">Thông tin sinh viên</li>
    </ol>
</div><!--/.row-->

<div>

    <dl class="dl-horizontal">
        <dt>
            Tên lớp
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LOP.TENLOP)
        </dd>

        <dt>
            Họ tên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HOTEN)
        </dd>

        <dt>
            Email
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMAIL)
        </dd>

        <dt>
            Số điện thoại
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDT)
        </dd>

        <dt>
            
        </dt>

        <dd>
            <button class="btn">@Html.ActionLink("Sửa", "Edit", new { id = Model.IDSV })</button>
            <button class="btn">@Html.ActionLink("Quay lại", "Index")</button>
        </dd>

    </dl>
</div>

QLHoiThaoProject/Areas/Admin/Views/SINHVIENs/Edit.cshtml
@model QLHoiThaoProject.Models.EFModel.SINHVIEN

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section IndexAdmin{
    Quản lý Sinh viên
}

<div class="row">
    <ol class="breadcrumb">
        <li class="active">Cập nhật thông tin sinh viên</li>
    </ol>
</div><!--/.row-->

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
  
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDSV)

        <div class="form-group">
            <div class="control-label col-md-2">Tên lớp</div>
            <div class="col-md-10">
                @Html.DropDownList("IDLOP", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDLOP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Họ tên</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.HOTEN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HOTEN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Email</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Số điện thoại</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button class="btn" type="submit">@Html.ActionLink("Hủy", "Index","SINHVIENs")</button>
                <input type="submit" value="Cập nhật" class="btn btn-default" />
            </div>
        </div>
    </div>
}

QLHoiThaoProject/Areas/Admin/Views/SINHVIENs/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model PagedList.PagedList<QLHoiThaoProject.Models.EFModel.SINHVIEN>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section IndexAdmin{
    Quản lý Sinh viên
}

<div class="row">
    <ol class="breadcrumb">
        <li class="active">Danh sách sinh viên</li>
    </ol>
</div><!--/.row-->
<div class="row">
    <div class="col-lg-6"></div>
    <div class="col-lg-1 btn">Tìm kiếm:</div>
    <div class="col-lg-5">
        @*<form role="search">*@
        @*<div class="form-group">*@
        <input type="text" class="form-control" id="SeachName" placeholder="Nhập thông tin cần tìm" />
        @*<button class="btn btn-default" id="btnSearch" type="submit">Search</button>*@
        @*</div>*@


    </div>

</div>
<p>
    <button class="btn btn-default" type="submit">@Html.ActionLink("Thêm sinh viên mới", "Create")</button>
</p>
<table class="table table-hover">
    <tr>
        <th>
            Tên lớp
        </th>
        <th>
            Họ tên
        </th>
        <th>
            Email
        </th>
        <th>
            Số điện thoại
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LOP.TENLOP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HOTEN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EMAIL)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SDT)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.IDSV }) |
                @Html.ActionLink("Chi tiết", "Details", new { id = item.IDSV }) |
                <a href="#" class="RemoveLink" data-id="@item.IDSV" data-username="@item.HOTEN">Xóa</a>
            </td>
        </tr>
    }

</table>
<div class="row">
    <div class="col-lg-3">
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/ @Model.PageCount
    </div>
    <div class="col-lg-3"></div>
    <div class="col-lg-3"></div>
    <div class="col-lg-3">Hiển thị @Model.Count/@ViewBag.Count sinh viên</div>
</div>

<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-3"></div>
    <div class="col-lg-3"></div>
    <div class="col-lg-3">
        <div>
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
        </div>
    </div>
</div>
<script type="text/javascript">
        $(function () {
            $('.RemoveLink').click(function () {
                var x = $(this).attr("data-id");
                var name = $(this).attr("data-username");
                if (confirm("Bạn có chắc xóa sinh viên " + name + "?")) {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("Delete", "SINHVIENs")',
                        data: { id: x },
                        success: function () {
                            alert("Xóa thành công!");
                            window.location.reload();
                        },
                    });
                }
            })

            $('#SeachName').keypress(function (event) {
                var keycode = (event.keyCode ? event.keyCode : event.which);
                if (keycode == '13') {
                    var Name = $('#SeachName').val();
                    var url = '@Url.Action("Search", "SINHVIENs", new { Name = "_Name" })'
                    var link = url.replace("_Name", Name);
                    location.href = link;
                }
            });
        })
</script>

QLHoiThaoProject/Areas/Admin/Views/SINHVIENs/Search.cshtml
@using PagedList;
@using PagedList.Mvc;
@model PagedList.PagedList<QLHoiThaoProject.Models.EFModel.SINHVIEN>

@{
    ViewBag.Title = "Search";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section IndexAdmin{
    Quản lý Sinh viên
}
<div class="row">
    <ol class="breadcrumb">
        <li class="active">Kết quả tìm kiếm</li>
    </ol>
</div><!--/.row-->
<div class="row">
    <div class="col-lg-6"></div>
    <div class="col-lg-1 btn">Tìm kiếm:</div>
    <div class="col-lg-5">
        @*<form role="search">*@
        @*<div class="form-group">*@
        <input type="text" class="form-control" id="SeachName" placeholder="Nhập thông tin cần tìm" />
        @*<button class="btn btn-default" id="btnSearch" type="submit">Search</button>*@
        @*</div>*@


    </div>

</div>
<p>
    <button class="btn btn-default" type="submit">@Html.ActionLink("Quay lại danh sách", "Index")</button>
</p>

Tìm được @ViewBag.Count kết quả
<table class="table table-hover">
    <tr>
        <th>
            Tên lớp
        </th>
        <th>
            Họ tên
        </th>
        <th>
            Email
        </th>
        <th>
            Số điện thoại
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LOP.TENLOP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HOTEN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EMAIL)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SDT)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.IDSV }) |
                @Html.ActionLink("Chi tiết", "Details", new { id = item.IDSV }) |
                <a href="#" class="RemoveLink" data-id="@item.IDSV" data-username="@item.HOTEN">Xóa</a>
            </td>
        </tr>
    }

</table>
<div class="row">
    <div class="col-lg-3">
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/ @Model.PageCount
    </div>
    <div class="col-lg-3"></div>
    <div class="col-lg-3"></div>
    <div class="col-lg-3">Hiển thị @Model.Count/@ViewBag.Count sinh viên</div>
</div>

<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-3"></div>
    <div class="col-lg-3"></div>
    <div class="col-lg-3">
        <div>
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
        </div>
    </div>
</div>
<script type="text/javascript">
        $(function () {
            $('.RemoveLink').click(function () {
                var x = $(this).attr("data-id");
                var name = $(this).attr("data-username");
                if (confirm("Bạn có chắc xóa sinh viên " + name + "?")) {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("Delete", "SINHVIENs")',
                        data: { id: x },
                        success: function () {
                            alert("Xóa thành công!");
                            window.location.reload();
                        },
                    });
                }
            })

            $('#SeachName').keypress(function (event) {
                var keycode = (event.keyCode ? event.keyCode : event.which);
                if (keycode == '13') {
                    var Name = $('#SeachName').val();
                    var url = '@Url.Action("Search", "SINHVIENs", new { Name = "_Name" })'
                    var link = url.replace("_Name", Name);
                    location.href = link;
                }
            });
        })
</script>