QLHoiThaoProject/Models/EFModel/CTTRANDAU.cs
namespace QLHoiThaoProject.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("CTTRANDAU")]
    public partial class CTTRANDAU
    {
        [Key]
        [Column(Order = 0)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int IDDOI { get; set; }

        [Key]
        [Column(Order = 1)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int IDTD { get; set; }

        [StringLength(255)]
        public string KETQUA { get; set; }

        [StringLength(255)]
        public string TISO { get; set; }

        public int? DIEM { get; set; }

        public virtual DOI DOI { get; set; }

        public virtual TRANDAU TRANDAU { get; set; }
    }
}

QLHoiThaoProject/Areas/Admin/Controllers/CTTRANDAUsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLHoiThaoProject.Models.EFModel;

namespace QLHoiThaoProject.Areas.Admin.Controllers
{
    public class CTTRANDAUsController : BaseController
    {
        private QLHoiThaoDbContext db = new QLHoiThaoDbContext();

        // GET: Admin/CTTRANDAUs1
        public ActionResult Index(int? id)//id vòng đấu
        {
            var cTTRANDAUs = db.CTTRANDAUs.Include(c => c.DOI).
                Include(c => c.TRANDAU).Where(c=>c.TRANDAU.TRANGTHAI==true).Where(c=>c.TRANDAU.IDVONGDAU==id);
            var tenmon = db.VONGDAUs.Where(v => v.IDVONGDAU == id).Select(v => new { TENMTD = v.MONTHIDAU.TENMTD }).SingleOrDefault();
            ViewData["TenMon"] = tenmon.TENMTD;
            return View(cTTRANDAUs.ToList());
        }

        public ActionResult TimHT_TranDau()
        {
            ViewBag.IDHT = db.HOITHAOs.ToList();
            return View();
        }

        public ActionResult TimMTD_TranDau(int? id)
        {
            //ViewBag.IDBANG = db.BANGDAUs.ToList();            
            var TENHT = db.HOITHAOs.Where(h => h.IDHT == id).Select(h => new { TENHT = h.TENHT }).SingleOrDefault();
            ViewData.Add("TenHT", TENHT.TENHT);
            var Mon = db.VONGDAUs.Where(v => v.IDHT == id).Select(v => new { IDMTD = v.MONTHIDAU.IDMTD, TENMTD = v.MONTHIDAU.TENMTD }).Distinct();
            ViewBag.IDMTD = new SelectList(Mon, "IDMTD", "TENMTD");

            var VONGDAU = db.VONGDAUs.Where(v => v.IDHT == id);
            ViewBag.VONGDAU = VONGDAU;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TimMTD_TranDau(int? id, int IDMTD)
        {
            //ViewBag.IDBANG = db.BANGDAUs.ToList();            
            var VONGDAU = db.VONGDAUs.Where(v => v.IDHT == id && v.IDMTD == IDMTD);
            ViewBag.VONGDAU = VONGDAU;

            var Mon = db.VONGDAUs.Where(v => v.IDHT == id).Select(v => new { IDMTD = v.MONTHIDAU.IDMTD, TENMTD = v.MONTHIDAU.TENMTD }).Distinct();
            ViewBag.IDMTD = new SelectList(Mon, "IDMTD", "TENMTD");
            return View();
        }

        public ActionResult LichTranDau(int? id)//id vong dau
        {
            //lấy hết các mẩu tin trong bảng cttrandau
            ViewBag.LICHDAU =
                db.CTTRANDAUs.Where(ct => ct.TRANDAU.VONGDAU.IDVONGDAU == id).OrderBy(ct => ct.TRANDAU.NGAYTHIDAU).ToList();

            //lấy hết các mẩu tin trong trận đấu
            var TranDau = db.TRANDAUs.Where(ct => ct.VONGDAU.IDVONGDAU == id && ct.TRANGTHAI==true).OrderBy(ct => ct.NGAYTHIDAU).ToList();

            List<string> listtrongtai = new List<string>();

            ViewBag.TRONGTAI = listtrongtai;
            //tổng số mẩu tin trong bảng trận đấu
            ViewBag.Total = TranDau.Count;

            ViewBag.TRANDAU = TranDau;

            return View();
        }

        public ActionResult Edit(int? id) {//id ma tran dau
            var trandau = db.TRANDAUs.Where(ct => ct.IDTD == id).OrderBy(ct => ct.NGAYTHIDAU).ToList().SingleOrDefault();
            ViewBag.TRAN = trandau;
            var cttran = db.CTTRANDAUs.Where(ct => ct.IDTD == id).ToList();
            ViewBag.CTTRAN = cttran;
            ViewData["tisodoi1"] = "";
            ViewData["tisodoi2"] = "";
            ViewData["diemdoi1"] = "";
            ViewData["diemdoi2"] = "";
            for (int a=0;a < cttran.Count-1;a++) {
                ViewData["tisodoi1"] = cttran[a].TISO;
                ViewData["tisodoi2"] = cttran[a+1].TISO;
                ViewData["diemdoi1"] = cttran[a].DIEM;
                ViewData["diemdoi2"] = cttran[a + 1].DIEM;
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id,int txtTiSo1, int txtTiSo2, int txtSoDiem1, int txtSoDiem2)
        {
            //CTTRANDAU ChiTiet = new CTTRANDAU();            
            var cttran = db.CTTRANDAUs.Where(ct => ct.IDTD == id).ToList();
            int a=0; int b=0;
            for (int i = 0; i < 1; i++)
            {
                a = cttran[i].IDDOI;//id doi 1
               b = cttran[i + 1].IDDOI;// id doi 2
            }
            CTTRANDAU ctt = db.CTTRANDAUs.Single(c => c.IDTD == id && c.IDDOI == a);
            ctt.TISO = txtTiSo1.ToString(); ctt.DIEM = txtSoDiem1;

            CTTRANDAU ctt1 = db.CTTRANDAUs.Single(c => c.IDTD == id && c.IDDOI == b);
            ctt1.TISO = txtTiSo2.ToString(); ctt1.DIEM = txtSoDiem2;

            db.SaveChanges();

            ViewBag.CTTRAN = db.CTTRANDAUs.Where(ct => ct.IDTD == id).ToList();
            ViewBag.DOITHANG = new SelectList(db.CTTRANDAUs.Where(c => c.IDTD == id).Select(c => new { IDDOI = c.IDDOI, TENDOI = c.DOI.TENDOI }), "IDDOI", "TENDOI");
            return View();
        }

        // GET: Admin/CTTRANDAUs1/Details/5
        public ActionResult Details(int? id, int? idtd)
        {
            if (id == null || idtd == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CTTRANDAU cTTRANDAU = db.CTTRANDAUs.Find(id,idtd);
            if (cTTRANDAU == null)
            {
                return HttpNotFound();
            }
            return View(cTTRANDAU);
        }

        // GET: Admin/CTTRANDAUs1/Create
        public ActionResult Create()
        {
            ViewBag.IDDOI = new SelectList(db.DOIs, "IDDOI", "TENDOI");
            ViewBag.IDTD = new SelectList(db.TRANDAUs, "IDTD", "THOIGIANBD");
            return View();
        }

        // POST: Admin/CTTRANDAUs1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDDOI,IDTD,KETQUA,TISO,DIEM")] CTTRANDAU cTTRANDAU)
        {
            if (ModelState.IsValid)
            {
                db.CTTRANDAUs.Add(cTTRANDAU);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IDDOI = new SelectList(db.DOIs, "IDDOI", "TENDOI", cTTRANDAU.IDDOI);
            ViewBag.IDTD = new SelectList(db.TRANDAUs, "IDTD", "THOIGIANBD", cTTRANDAU.IDTD);
            return View(cTTRANDAU);
        }

        // GET: Admin/CTTRANDAUs1/Edit/5
        //public ActionResult Edit(int? id, int? idtd)
        //{
        //    if (id == null || idtd == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    CTTRANDAU cTTRANDAU = db.CTTRANDAUs.Find(id,idtd);
        //    if (cTTRANDAU == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.IDDOI = new SelectList(db.DOIs, "IDDOI", "TENDOI", cTTRANDAU.IDDOI);
        //    ViewBag.IDTD = new SelectList(db.TRANDAUs, "IDTD", "THOIGIANBD", cTTRANDAU.IDTD);
        //    return View(cTTRANDAU);
        //}

        //// POST: Admin/CTTRANDAUs1/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "IDDOI,IDTD,KETQUA,TISO,DIEM")] CTTRANDAU cTTRANDAU)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(cTTRANDAU).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.IDDOI = new SelectList(db.DOIs, "IDDOI", "TENDOI", cTTRANDAU.IDDOI);
        //    ViewBag.IDTD = new SelectList(db.TRANDAUs, "IDTD", "THOIGIANBD", cTTRANDAU.IDTD);
        //    return View(cTTRANDAU);
        //}

        // GET: Admin/CTTRANDAUs1/Delete/5
        public ActionResult Delete(int? id, int? idtd)
        {
            if (id == null || idtd == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CTTRANDAU cTTRANDAU = db.CTTRANDAUs.Find(id,idtd);
            if (cTTRANDAU == null)
            {
                return HttpNotFound();
            }
            return View(cTTRANDAU);
        }

        // POST: Admin/CTTRANDAUs1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, int? idtd)
        {
            CTTRANDAU cTTRANDAU = db.CTTRANDAUs.Find(id, idtd);
            db.CTTRANDAUs.Remove(cTTRANDAU);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLHoiThaoProject/Areas/Admin/Views/CTTRANDAUs/Create.cshtml
@model QLHoiThaoProject.Models.EFModel.CTTRANDAU

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CTTRANDAU</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IDDOI, "IDDOI", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDDOI", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDDOI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDTD, "IDTD", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDTD", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDTD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KETQUA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KETQUA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KETQUA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TISO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TISO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TISO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DIEM, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DIEM, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DIEM, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

QLHoiThaoProject/Areas/Admin/Views/CTTRANDAUs/Delete.cshtml
@model QLHoiThaoProject.Models.EFModel.CTTRANDAU

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CTTRANDAU</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DOI.TENDOI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOI.TENDOI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TRANDAU.THOIGIANBD)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TRANDAU.THOIGIANBD)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KETQUA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KETQUA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TISO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TISO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DIEM)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DIEM)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

QLHoiThaoProject/Areas/Admin/Views/CTTRANDAUs/Details.cshtml
@model QLHoiThaoProject.Models.EFModel.CTTRANDAU

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


@section IndexAdmin{
    Quản lý trận đấu
}


<div class="row">
    <ol class="breadcrumb">
        <li class="active">Chi tiết trận đấu</li>
    </ol>
</div><!--/.row-->

<div>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DOI.TENDOI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOI.TENDOI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TRANDAU.THOIGIANBD)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TRANDAU.THOIGIANBD)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KETQUA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KETQUA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TISO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TISO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DIEM)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DIEM)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

QLHoiThaoProject/Areas/Admin/Views/CTTRANDAUs/Edit.cshtml
@{
    ViewBag.Title = "LichTranDau";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section IndexAdmin{
    Cập nhật kết quả thi đấu
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <table class="table table-hover">
        
        @for (var i = 0; i < 1; i++)
        {
            @*@Html.Hidden("IDTD", ViewData["IDTD"])*@
            <tr>
                <th>Môn thi đấu</th>
                <td colspan="2"><div class="form-control disabled">@ViewBag.CTTRAN[i].DOI.MONTHIDAU.TENMTD</div></td>
            </tr>
            <tr>
                <th>Vòng đấu</th>
                <td colspan="2"><div class="form-control disabled">@ViewBag.CTTRAN[i].TRANDAU.VONGDAU.TENVONGDAU</div></td>
            </tr>
            <tr>
                <th>Bảng đấu</th>
                <td colspan="2"><div class="form-control disabled">@ViewBag.CTTRAN[i].DOI.BANGDAU.TENBANG</div></td>
            </tr>            
            <tr>
                <th>Đội thi đấu</th>
                <td align="center">
                    <div class="form-control disabled">@ViewBag.CTTRAN[i].DOI.TENDOI</div>
                </td>
                <td align="center"><div class="form-control disabled">@ViewBag.CTTRAN[i + 1].DOI.TENDOI</div></td>
            </tr>
            <tr>
                <th>Tỉ số</th>
                <td>@Html.TextBox("txtTiSo1", ViewData["tisodoi1"], htmlAttributes: new { @class = "form-control"})</td>
                <td>@Html.TextBox("txtTiSo2", ViewData["tisodoi2"], htmlAttributes: new { @class = "form-control" })</td>
            </tr>
            <tr>
                <th>Điểm</th>
                <td>@Html.TextBox("txtSoDiem1", ViewData["diemdoi1"], htmlAttributes: new { @class = "form-control" })</td>
                <td>@Html.TextBox("txtSoDiem2", ViewData["diemdoi2"], htmlAttributes: new { @class = "form-control" })</td>
            </tr>            
            <tr>
                <th>Trọng tài</th>
                <td colspan="2"><div class="form-control disabled">@ViewBag.CTTRAN[i].TRANDAU.TRONGTAI.TENTRONGTAI</div></td>
            </tr>
            <tr>
                <th>Sân thi đấu</th>
                <td colspan="2"><div class="form-control disabled">@ViewBag.CTTRAN[i].TRANDAU.SANTHIDAU.TENSTD</div></td>
            </tr>
            <tr>
                <th>Ngày thi đấu</th>
                <td colspan="2"><div class="form-control disabled">@ViewBag.CTTRAN[i].TRANDAU.NGAYTHIDAU</div></td>
            </tr>
            <tr>
                <th>Thời gian</th>
                <td colspan="2"><div class="form-control disabled">@ViewBag.CTTRAN[i].TRANDAU.THOIGIANBD - @ViewBag.CTTRAN[i].TRANDAU.THOIGIANKT</div></td>
            </tr>                
            <tr>
                <th></th>
                <td colspan="2">
                    <a class="btn btn-default" href="@Url.Action("TimHT_TranDau","CTTRANDAUs")">Trở về</a>
                    <input type="submit" name="btnCapNhat" value="Cập nhật" class="btn btn-primary" />
                </td>
            </tr>
        }
    </table>
    
}

QLHoiThaoProject/Areas/Admin/Views/CTTRANDAUs/Index.cshtml
@model IEnumerable<QLHoiThaoProject.Models.EFModel.CTTRANDAU>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section IndexAdmin{
    Quản lý trận đấu
}
<div class="row">
    <ol class="breadcrumb">
        <li class="active">Chi tiết trận đấu của môn @ViewData["TenMon"]</li>
    </ol>
</div><!--/.row-->

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TRANDAU.VONGDAU.TENVONGDAU)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DOI.TENDOI)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TRANDAU.THOIGIANBD)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.KETQUA)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TISO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DIEM)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <th>
            @Html.DisplayFor(modelItem => item.TRANDAU.VONGDAU.TENVONGDAU)
        </th>
        <td>
            @Html.DisplayFor(modelItem => item.DOI.TENDOI)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TRANDAU.THOIGIANBD)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.KETQUA)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TISO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DIEM)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.IDDOI, idtd=item.IDTD }) |
            @Html.ActionLink("Details", "Details", new { id = item.IDDOI, idtd = item.IDTD })
            @*@Html.ActionLink("Delete", "Delete", new { id = item.IDDOI, idtd = item.IDTD })*@
        </td>
    </tr>
}

</table>

QLHoiThaoProject/Areas/Admin/Views/CTTRANDAUs/LichTranDau.cshtml
@{
    ViewBag.Title = "LichTranDau";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section IndexAdmin{
    Cập nhật kết quả thi đấu
}

<div class="row">
    <ol class="breadcrumb">
        <li class="active">Danh sách trận đấu</li>
    </ol>
</div><!--/.row-->
<div>
    <table class="table table-hover">
        <tr>
            <th>
                Môn thi đấu
            </th>
            <th>
                Vòng đấu
            </th>   
            <th>
                Mã trận đấu
            </th>  
            <th>
                Tên bảng đấu
            </th>  
            <th>
                Ngày thi đấu
            </th>  
            <th>Thời gian</th>
            <th>
                Sân thi đấu
            </th>  
            <th>
                Đội thi đấu
            </th>  
            <th>
                Tỉ số
            </th> 
            <th>
                Cập nhật
            </th>           
        </tr>
        @for (var i = 0; i < ViewBag.Total; i++)
        {
            <tr>
                <td>
                    @ViewBag.LICHDAU[i].DOI.MONTHIDAU.TENMTD
                </td>
                <td>
                    @ViewBag.TRANDAU[i].VONGDAU.TENVONGDAU  
                </td>
                <td>
                    @ViewBag.TRANDAU[i].IDTD
                </td>
               <td>
                    @ViewBag.LICHDAU[i].DOI.BANGDAU.TENBANG
                </td>
                <td>
                    @ViewBag.TRANDAU[i].NGAYTHIDAU
                </td>
                <td>@ViewBag.TRANDAU[i].THOIGIANBD - @ViewBag.TRANDAU[i].THOIGIANKT</td>
                <td>
                    @ViewBag.TRANDAU[i].SANTHIDAU.TENSTD
                </td>
                <td>
                    @ViewBag.LICHDAU[i].DOI.TENDOI - @ViewBag.LICHDAU[i + 1].DOI.TENDOI                                        
                </td>
                <td>@ViewBag.LICHDAU[i].TISO - @ViewBag.LICHDAU[i + 1].TISO</td>
                <td>
                    @Html.ActionLink("Cập nhật", "Edit", new { id= ViewBag.TRANDAU[i].IDTD})
                </td>
            </tr>
        }
    </table>
</div>

QLHoiThaoProject/Areas/Admin/Views/CTTRANDAUs/TimHT_TranDau.cshtml
@model IEnumerable<QLHoiThaoProject.Models.EFModel.DOI>

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section IndexAdmin{
    Cập nhật kết quả thi đấu
}

<div class="row">
    <ol class="breadcrumb">
        <li class="active">Chọn kỳ hội thao</li>
    </ol>
</div><!--/.row-->

<div>

    <table class="table table-hover">
        <tr>
            <th>
                Mã hội thao
            </th>
            <th>
                Tên hội thao
            </th>

            <th></th>
        </tr>
        @foreach (var item in ViewBag.IDHT)
        {
            <tr>
                <td>
                    @item.IDHT
                </td>
                <td>
                    @item.TENHT
                </td>
                <td>
                    @Html.ActionLink("Chọn", "TimMTD_TranDau", new { id = item.IDHT })
                </td>
            </tr>
        }
    </table>
</div>

QLHoiThaoProject/Areas/Admin/Views/CTTRANDAUs/TimMTD_TranDau.cshtml
@model QLHoiThaoProject.Models.EFModel.TRANDAU

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section IndexAdmin{
    Cập nhật kết quả trận đấu
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-md-2 pull-left">Chọn môn thi đấu:</div>
        <div class="col-md-4">@Html.DropDownList("IDMTD", (SelectList)ViewBag.IDMTD, htmlAttributes: new { @class = "form-control" })</div>
        <div class="col-md-4 pull-left"><input type="submit" value="Chọn" class="btn btn-default" /></div>
    </div>
}
<hr />
<div class="row">
    <ol class="breadcrumb">
        <li class="active">Danh sách vòng đấu</li>
    </ol>
</div><!--/.row-->
<table class="table table-hover">
    <tr>
        <th>Vòng đấu</th>
        <th>Tùy chọn</th>
    </tr>
    @foreach (var item in ViewBag.VONGDAU)
    {
        <tr>
            <td>@item.TENVONGDAU </td>
            <td>@Html.ActionLink("Chọn", "LichTranDau", new { id = item.IDVONGDAU })</td>
        </tr>
    }
</table>