QLHoiThaoProject/Models/EFModel/COMTD.cs
namespace QLHoiThaoProject.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("COMTD")]
    public partial class COMTD
    {
        [Key]
        [Column(Order = 0)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int IDMTD { get; set; }

        [Key]
        [Column(Order = 1)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int IDHT { get; set; }

        [StringLength(255)]
        public string GHICHU { get; set; }

        public virtual MONTHIDAU MONTHIDAU { get; set; }

        public virtual HOITHAO HOITHAO { get; set; }
    }
}

QLHoiThaoProject/Areas/Admin/Controllers/COMTDsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLHoiThaoProject.Models.EFModel;
using PagedList;

namespace QLHoiThaoProject.Areas.Admin.Controllers
{
    public class COMTDsController : BaseController
    {
        private QLHoiThaoDbContext db = new QLHoiThaoDbContext();

        // GET: Admin/COMTDs
        public ActionResult Index(int? page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 3;
            ViewBag.Count = db.COMTDs.Include(c => c.HOITHAO).Include(c => c.MONTHIDAU).ToList().Count;
            return View(db.COMTDs.Include(c => c.HOITHAO).Include(c => c.MONTHIDAU).ToList().ToPagedList(pageNumber, pageSize));
        }
        // GET: Admin/COMTDs/Details/5
        public ActionResult Details(int? id, int? idht)
        {
            if (id == null || idht==null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            COMTD cOMTD = db.COMTDs.Find(id,idht);
            if (cOMTD == null)
            {
                return HttpNotFound();
            }
            return View(cOMTD);
        }

        // GET: Admin/COMTDs/Create
        public ActionResult Create()
        {
            ViewBag.IDHT = new SelectList(db.HOITHAOs, "IDHT", "TENHT");
            ViewBag.IDMTD = new SelectList(db.MONTHIDAUs, "IDMTD", "TENMTD");
            return View();
        }

        // POST: Admin/COMTDs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDHT,IDMTD,GHICHU")] COMTD cOMTD)
        {
            if (ModelState.IsValid)
            {
                db.COMTDs.Add(cOMTD);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IDHT = new SelectList(db.HOITHAOs, "IDHT", "TENHT", cOMTD.IDHT);
            ViewBag.IDMTD = new SelectList(db.MONTHIDAUs, "IDMTD", "TENMTD", cOMTD.IDMTD);
            return View(cOMTD);
        }

        // GET: Admin/COMTDs/Edit/5
        public ActionResult Edit(int? id, int? idht)
        {
            if (id == null || idht==null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            COMTD cOMTD = db.COMTDs.Find(id, idht);
            if (cOMTD == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDHT = new SelectList(db.HOITHAOs, "IDHT", "TENHT", cOMTD.IDHT);
            ViewBag.IDMTD = new SelectList(db.MONTHIDAUs, "IDMTD", "TENMTD", cOMTD.IDMTD);
            return View(cOMTD);
        }

        // POST: Admin/COMTDs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDHT,IDMTD,GHICHU")] COMTD cOMTD)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cOMTD).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDHT = new SelectList(db.HOITHAOs, "IDHT", "TENHT", cOMTD.IDHT);
            ViewBag.IDMTD = new SelectList(db.MONTHIDAUs, "IDMTD", "TENMTD", cOMTD.IDMTD);
            return View(cOMTD);
        }

        // GET: Admin/COMTDs/Delete/5
        public ActionResult Delete(int? id, int? idht)
        {
            if (id == null || idht==null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            COMTD cOMTD = db.COMTDs.Find(id,idht);
            if (cOMTD == null)
            {
                return HttpNotFound();
            }
            return View(cOMTD);
        }

        // POST: Admin/COMTDs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, int idht)
        {
            COMTD cOMTD = db.COMTDs.Find(id,idht);
            db.COMTDs.Remove(cOMTD);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLHoiThaoProject/Areas/Admin/Views/COMTDs/Create.cshtml
@model QLHoiThaoProject.Models.EFModel.COMTD

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


@section IndexAdmin{
    Quản lý DS Môn thi đấu trong hội thao
}

<div class="row">
    <ol class="breadcrumb">
        <li class="active">Thêm mới</li>
    </ol>
</div><!--/.row-->

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="control-label col-md-2">Tên hội thao</div>
            <div class="col-md-10">
                @Html.DropDownList("IDHT", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDHT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Tên môn thi đấu</div>
            <div class="col-md-10">
                @Html.DropDownList("IDMTD", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDMTD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Ghi chú</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.GHICHU, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GHICHU, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button class="btn" type="submit">@Html.ActionLink("Hủy", "Index", "COMTDs")</button>
                <input type="submit" value="Thêm" class="btn btn-default" />
            </div>
        </div>
    </div>
}

QLHoiThaoProject/Areas/Admin/Views/COMTDs/Delete.cshtml
@model QLHoiThaoProject.Models.EFModel.COMTD

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


@section IndexAdmin{
    Quản lý DS Môn thi đấu trong hội thao
}
<h3>Bạn có chắc muốn xóa?</h3>
<div>

    <dl class="dl-horizontal">
        <dt>
            Tên hội thao
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HOITHAO.TENHT)
        </dd>

        <dt>
            Tên môn thi đấu
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MONTHIDAU.TENMTD)
        </dd>

        <dt>
            Ghi chú
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GHICHU)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Quay lại", "Index")
        </div>
    }
</div>

QLHoiThaoProject/Areas/Admin/Views/COMTDs/Details.cshtml
@model QLHoiThaoProject.Models.EFModel.COMTD

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


@section IndexAdmin{
    Quản lý DS Môn thi đấu trong hội thao
}
<div class="row">
    <ol class="breadcrumb">
        <li class="active">Thông tin DS Môn thi đấu trong hội thao</li>
    </ol>
</div><!--/.row-->

<div>
  
    <dl class="dl-horizontal">
        <dt>
            Tên hội thao
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HOITHAO.TENHT)
        </dd>

        <dt>
            Tên môn thi đấu
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MONTHIDAU.TENMTD)
        </dd>

        <dt>
            Ghi chú
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GHICHU)
        </dd>

        <dt>
            
        </dt>

        <dd>
            <button class="btn">@Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ })</button>
            <button class="btn">@Html.ActionLink("Back to List", "Index")</button>
        </dd>

    </dl>
</div>

QLHoiThaoProject/Areas/Admin/Views/COMTDs/Edit.cshtml
@model QLHoiThaoProject.Models.EFModel.COMTD

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


@section IndexAdmin{
    Quản lý Môn thi đấu trong hội thao
}
<div class="row">
    <ol class="breadcrumb">
        <li class="active">Cập nhật Môn thi đấu trong hội thao</li>
    </ol>
</div><!--/.row-->

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
  
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*@Html.HiddenFor(model => model.IDHT)

        @Html.HiddenFor(model => model.IDMTD)*@

        <div class="form-group" hidden>
            <div class="control-label col-md-2">Tên hội thao</div>
            <div class="col-md-10">
                @Html.DropDownList("IDHT", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDHT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" hidden>
            <div class="control-label col-md-2">Tên môn thi đấu</div>
            <div class="col-md-10">
                @Html.DropDownList("IDMTD", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDMTD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Ghi chú</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.GHICHU, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GHICHU, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button class="btn" type="submit">@Html.ActionLink("Hủy", "Index", "COMTDs")</button>
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

QLHoiThaoProject/Areas/Admin/Views/COMTDs/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model PagedList.PagedList<QLHoiThaoProject.Models.EFModel.COMTD>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section IndexAdmin{
    Quản lý Môn thi đấu trong hội thao
}
<div class="row">
    <ol class="breadcrumb">
        <li class="active">Danh sách Môn thi đấu trong hội thao</li>
    </ol>
</div><!--/.row-->

<p>
    <button class="btn btn-default" type="submit">@Html.ActionLink("Thêm mới", "Create")</button>
</p>

<table class="table table-hover">
    <tr>
        <th>
            Tên hội thao
        </th>
        <th>
            Tên môn thi đấu
        </th>
        <th>
            Ghi chú
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.HOITHAO.TENHT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MONTHIDAU.TENMTD)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GHICHU)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id=item.IDMTD, idht=item.IDHT }) |
                @Html.ActionLink("Chi tiết", "Details", new { id = item.IDMTD, idht = item.IDHT }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.IDMTD, idht = item.IDHT })
            </td>
        </tr>
    }

</table>
<div class="row">
    <div class="col-lg-3">
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/ @Model.PageCount
    </div>
    <div class="col-lg-3"></div>
    <div class="col-lg-3"></div>
    <div class="col-lg-3">Hiển thị @Model.Count/@ViewBag.Count dòng</div>
</div>

<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-3"></div>
    <div class="col-lg-3"></div>
    <div class="col-lg-3">
        <div>
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
        </div>
    </div>
</div>